name: anagram
description: A simple standalone commandline anagram solving utility library for Dart.
version: 2.1.4
homepage: https://github.com/shamblett/anagram

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 path: '^1.8.2'
 meta: '^1.8.0'
 args: '^2.3.1'

executables:
 anagram:

dev_dependencies:
  lints: '^2.0.0'






