name: anagram
description: A simple standalone commandline anagram solving utility library for Dart.
version: 3.0.0
homepage: https://github.com/shamblett/anagram

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.0.0 <4.0.0'

dependencies:
 path: '^1.8.3'
 meta: '^1.9.0'
 args: '^2.4.1'

executables:
 anagram:

dev_dependencies:
  lints: '^2.1.0'






