name: anagram
description: A simple standalone anagram solving utility library for Dart.
version: 1.0.0
homepage: https://github.com/shamblett/anagram

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 path: '^1.6.4'
 meta: '^1.1.8'
 args: '^1.6.0'

dev_dependencies:
 pedantic: '^1.9.0'
 pana: '^0.13.5'





