name: anagram
description: A simple standalone commandline anagram solving utility library for Dart.
version: 3.0.3
homepage: https://github.com/shamblett/anagram

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.7.0 <4.0.0'

dependencies:
 path: '^1.9.1'
 meta: '^1.16.0'
 args: '^2.7.0'

executables:
 anagram:

dev_dependencies:
  lints: '^5.1.1'
  dart_code_metrics_presets: '^2.22.0'






