name: anagram
description: A simple standalone commandline anagram solving utility library for Dart.
version: 2.1.2
homepage: https://github.com/shamblett/anagram

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 path: '^1.6.4'
 meta: '^1.1.8'
 args: '^2.0.0'

executables:
 anagram:

dev_dependencies:
 pedantic: '^1.11.0'





